# deploy database 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-db2
  namespace: sut
  labels:
    tier: database
    family: db2
    apankura: 'v1'
spec:
  replicas: 1
  selector:
    matchLabels:
      key: pod-db2
  template:
    metadata:
      labels:
        key: pod-db2
    spec:
      volumes:
      - name: db2-volume
        emptyDir: {}
      containers:
        - name: db
          image: apankura/java-spring-gradle-one-db2-db2
          ports:
            - containerPort: 50000
          env:
            - name: "LICENSE"
              value: "accept"
            - name: "DB2INST1_PASSWORD"
              value: "admin123"
            - name: "DBNAME"
              value: "sutdb"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /database
              name: db2-volume
          readinessProbe:
            tcpSocket:
                port: 50000
            initialDelaySeconds: 5
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
    name: service-db2-session
    namespace: sut
spec:  
    type: ClusterIP
    selector:
        key: pod-db2
    ports:
    - name: host
      protocol: TCP      
      port: 48100
      targetPort: 50000

---
# deployment api

apiVersion: apps/v1
kind: Deployment
metadata:
    name: spring-session-deployment
    namespace: sut
    labels:
        tier: api
        family: spring        
        apankura: 'v1'
spec:
    replicas: 1
    selector:
        matchLabels:
            key: spring-session-pod
    template:
        metadata:
            labels:
                key: spring-session-pod
        spec:
            containers:
            - name: sut-container
              image: apankura/java-spring-gradle-one-db2-spring
              imagePullPolicy: Always
              ports:
              - containerPort: 48601    
              env:
                - name: "SPRING_PROFILES_ACTIVE"
                  value: "k8s"
                - name: "DB2_HOST"
                  value: "k8s" 
            
---

apiVersion: v1
kind: Service
metadata:
    name: service-sut
    namespace: sut
    labels:
        apankura: 'v1'
        tier: api
spec:  
    type: ClusterIP
    selector:
        key: spring-session-pod
    ports:
    - name: site
      protocol: TCP      
      port: 48100
      targetPort: 46801
