name: Build Apankura Image
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:      
      name: Build      
      runs-on: ubuntu-latest
      steps:        
        - name: docker version        
          run: docker --version
        - name: docker compose build        
          run: bash ./DB2/containers/build.sh