name: Build Apankura Image
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:      
      name: Build      
      runs-on: ubuntu-latest
      steps:        
        - uses: actions/checkout@v2
        - name: docker version        
          run: docker --version
        - name: current directory
          run: pwd
        - name: list directory
          run: ls
        - name: docker compose build                  
          working-directory: ./DB2/containers
          run: docker-compose build