name: Build Apankura DB2 Image

on:
  push:
    branches: [ master ]
    paths:
    - 'DB2/**'  

jobs:
    build_db2:
      name: Build DB2   
      runs-on: ubuntu-latest
      steps:        
        - uses: actions/checkout@v2
        - name: docker version        
          run: docker --version
        - name: current directory
          run: pwd
        - name: list directory
          run: ls          
        - name: docker compose build                  
          working-directory: ./DB2/containers
          run: docker-compose build
        - name: docker login
          run: docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"
        - name: docker tag
          run: |
                  docker tag sut/db2 apankura/java-spring-gradle-one-db2-db2:latest
                  docker tag sut/db2 apankura/java-spring-gradle-one-db2-db2:${{ github.sha }}                  
                  docker push apankura/java-spring-gradle-one-db2-db2
  
      